name: Build

on:
  push:
    branches: 
      - fix-ci
  repository_dispatch:
    types: do-something

jobs:
  automation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
      git fetch --prune --unshallow
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: '12.X'
    #     architecture: x64
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    # - name: Lint
    #   run: |
    #     npm run lint
    # - name: Test
    #   run: |
    #     npm run test:full
    # - name: Build
    #   run: |
    #     npm run build
    - name: Prepare Pull Request
      id: vars
      uses: ./.github/actions/prepare-pr
      env:
        CI: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        assignees: ci010
        reviewers: ci010
        branch: prepare-release
        title: ${{ steps.vars.outputs.title }}
        body: ${{ steps.vars.outputs.body }}
        commit-message: ${{ steps.vars.outputs.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Upload Coverage
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: coverage
    #     path: coverage


