name: Deploy Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  page-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    - name: Build Github Pages
      run: |
        npm run build:web
    - name: Build Typedoc documentation
      run: |
        npm run build:docs
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: docs/build
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
