name: Release

on:
  pull_request:
    types: [closed] 
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged && github.head_ref == 'prepare-release' && github.event.pull_request.user == 'github-actions[bot]'

    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.sha	}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm install
      env:
        CI: true
    - name: Compile All
      run: |
        npm run compile
    - name: Publish
      run: |
        lerna publish from-package --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Delete PR head branch
      uses: dawidd6/action-delete-branch@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.pull_request.head.ref }}
        be_kind: true # don't fail on errors (optional)
