name: Release

on:
  pull_request:
    types: [closed] 
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    # if: github.event.pull_request.merged && github.ref.startsWith('release')

    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Job Context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Runner Context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Update Remote
      run: |
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/voxelum/minecraft-launcher-core-node.git"
        git checkout origin/master
        git config user.name ci010
        git config user.email cijhn@hotmail.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm install
      env:
        CI: true
    - name: Build
      run: |
        npm run build
    - name: Publish
      run: |
        echo pub!
        # npx lerna publish --no-push from-package --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
