name: Release

on:
  pull_request:
    types: [closed] 
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged && github.head_ref == 'prepare-release' && github.event.pull_request.user.login == 'github-actions[bot]'

    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha	}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    - name: Compile All
      run: |
        npm run compile
    - name: Publish
      run: |
        git reset --hard
        npm run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish Tag
      run: |
        node --eval "console.log(JSON.parse(require('fs').readFileSync('package.json').toString()).version)" > tag.log
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/voxelum/minecraft-launcher-core-node.git"
        git config user.name ci010
        git config user.email cijhn@hotmail.com
        git tag -f $(cat tag.log)
        git push origin tag $(cat tag.log) -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Delete PR head branch
      uses: dawidd6/action-delete-branch@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: prepare-release
        be_kind: true # don't fail on errors (optional)
