name: Release Pre-Check

on:
  push:
    branches: 
      - master
    paths:
      - 'packages/*/*.ts'

jobs:
  automation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '12.X'
        architecture: x64
    - name: Install
      run: |
        npm install
      env:
        CI: true
    - name: Lint
      run: |
        npm run lint
    - name: Compile All
      run: |
        npm run compile
    - name: Test
      run: |
        npm run test
    - name: Prepare Pull Request 
      run: |
        node bump.js
      env:
        CI: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: "chore: bump version"
        PULL_REQUEST_TITLE: Prepare Release
        PULL_REQUEST_BODY: >
            This PR is auto-generated by
            [create-pull-request](https://github.com/peter-evans/create-pull-request)
            to prepare new releases for changed packages.
        PULL_REQUEST_ASSIGNEES: ci010
        PULL_REQUEST_REVIEWERS: ci010
        PULL_REQUEST_BRANCH: prepare-release
        BRANCH_SUFFIX: none
    - name: Update Tag
      run: |
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/voxelum/minecraft-launcher-core-node.git"
        git config user.name ci010
        git config user.email cijhn@hotmail.com
        git tag -f @xmcl/minecraft-launcher-core@$(cat tag.log)
        git push origin tag @xmcl/minecraft-launcher-core@$(cat tag.log) -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


