name: Release Autamation

on:
  push:
    branches: 
      - dev
    paths:
      - 'packages/*/*.ts'

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [10.x]

    # steps:
    # - uses: actions/checkout@v1
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: '12.X'
    #     architecture: x64
    # - name: Install
    #   run: |
    #     npm install
    #   env:
    #     CI: true
    # - name: Lint
    #   run: |
    #     npm run lint
    # - name: Build
    #   run: |
    #     npm run build
    # - name: Test
    #   run: |
    #     npm run test
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    # needs: build
    steps:
    - uses: actions/checkout@v1
      # with:
      #   ref: master
    # - name: Update Remote
    #   run: |
    #     git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/voxelum/minecraft-launcher-core-node.git"
    #     git checkout origin/master
    #     git config user.name ci010
    #     git config user.email cijhn@hotmail.com
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm install
      env:
        CI: true
    - name: Compile Project
      run: |
        npm run build
    - name: Bump Version 
      run: |
        npm run bump
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: "chore: bump version"
        PULL_REQUEST_BODY: >
            This PR is auto-generated by
            [create-pull-request](https://github.com/peter-evans/create-pull-request)
            to prepare a new release for packages.
        PULL_REQUEST_TITLE: 'Release'
        PULL_REQUEST_ASSIGNEES: ci010
        PULL_REQUEST_REVIEWERS: ci010
        PULL_REQUEST_BRANCH: release
