name: Pull Request Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use npm 7
      run: npm install -g npm@7
    - uses: actions/setup-java@v1
      with:
        java-version: '12.X'
        architecture: x64
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    - name: Lint and Compile
      run: |
        npm run lint
        npm run compile:dry
    - name: Test
      run: |
        npm run build:clean
        npm run test:full
      env:
        CI: true
    - name: Upload Coverage
      uses: actions/upload-artifact@master
      with:
        name: coverage
        path: coverage

